export type MediaAsset = {
  id: string;
  publicPath: string;
  sourcePath: string;
  kind: "image" | "video" | "icon" | "track";
  width: number | null;
  height: number | null;
  bytes: number;
  use: string;
  loading: "eager" | "metadata" | "lazy" | "lazy-near-section" | "route-priority" | "after-lcp" | "explicit-play" | "with-film";
  fallback: string | null;
  provenance: string;
};

export const mediaManifest = [
  {
    "id": "favicon-svg",
    "publicPath": "/media/favicon.svg",
    "sourcePath": "assets/images/favicon.svg",
    "kind": "icon",
    "width": null,
    "height": null,
    "bytes": 252,
    "use": "site chrome",
    "loading": "eager",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "favicon-32-png",
    "publicPath": "/media/favicon-32.png",
    "sourcePath": "assets/images/favicon-32.png",
    "kind": "image",
    "width": 32,
    "height": 32,
    "bytes": 538,
    "use": "site chrome",
    "loading": "eager",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "favicon-192-png",
    "publicPath": "/media/favicon-192.png",
    "sourcePath": "assets/images/favicon-192.png",
    "kind": "image",
    "width": 192,
    "height": 192,
    "bytes": 3022,
    "use": "site chrome",
    "loading": "eager",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "apple-touch-icon-png",
    "publicPath": "/media/apple-touch-icon.png",
    "sourcePath": "assets/images/apple-touch-icon.png",
    "kind": "image",
    "width": 180,
    "height": 180,
    "bytes": 2525,
    "use": "site chrome",
    "loading": "eager",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "iffykhan-og-jpg",
    "publicPath": "/media/iffykhan-og.jpg",
    "sourcePath": "assets/images/iffykhan-og.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 64030,
    "use": "shared social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "fallback-iffy-jpg",
    "publicPath": "/media/fallback-iffy.jpg",
    "sourcePath": "assets/images/fallback-iffy.jpg",
    "kind": "image",
    "width": 480,
    "height": 720,
    "bytes": 34149,
    "use": "hero and about fallback",
    "loading": "eager",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "iffy-laptop-webp",
    "publicPath": "/media/iffy-laptop.webp",
    "sourcePath": "assets/images/iffy-laptop.webp",
    "kind": "image",
    "width": 1068,
    "height": 1600,
    "bytes": 78128,
    "use": "consultation and about",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "iffy-hero-poster-webp",
    "publicPath": "/media/iffy-hero-poster.webp",
    "sourcePath": "public/media/iffy-hero.mp4 at 3.25 seconds",
    "kind": "image",
    "width": 480,
    "height": 848,
    "bytes": 22456,
    "use": "homepage LCP poster",
    "loading": "eager",
    "fallback": null,
    "provenance": "Derived from repository video"
  },
  {
    "id": "ik-logo-png",
    "publicPath": "/media/ik-logo.png",
    "sourcePath": "User supplied IK Logo/2.png",
    "kind": "image",
    "width": 512,
    "height": 468,
    "bytes": 14298,
    "use": "site header brand mark",
    "loading": "eager",
    "fallback": null,
    "provenance": "User-supplied brand asset"
  },
  {
    "id": "iffy-event-webp",
    "publicPath": "/media/iffy-event.webp",
    "sourcePath": "assets/images/iffy-event.webp",
    "kind": "image",
    "width": 900,
    "height": 599,
    "bytes": 32172,
    "use": "about",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "kamani-guest-1-webp",
    "publicPath": "/media/kamani-guest-1.webp",
    "sourcePath": "assets/images/kamani-guest-1.webp",
    "kind": "image",
    "width": 960,
    "height": 1280,
    "bytes": 92884,
    "use": "about relationship gallery",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Repository asset, context not independently verified"
  },
  {
    "id": "kamani-guest-2-webp",
    "publicPath": "/media/kamani-guest-2.webp",
    "sourcePath": "assets/images/kamani-guest-2.webp",
    "kind": "image",
    "width": 1280,
    "height": 853,
    "bytes": 54896,
    "use": "about relationship gallery",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Repository asset, context not independently verified"
  },
  {
    "id": "kamani-guest-3-webp",
    "publicPath": "/media/kamani-guest-3.webp",
    "sourcePath": "assets/images/kamani-guest-3.webp",
    "kind": "image",
    "width": 1280,
    "height": 852,
    "bytes": 59580,
    "use": "about relationship gallery",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Repository asset, context not independently verified"
  },
  {
    "id": "hero-downtown-webp",
    "publicPath": "/media/hero-downtown.webp",
    "sourcePath": "assets/images/hero-downtown.webp",
    "kind": "image",
    "width": 1600,
    "height": 2132,
    "bytes": 320962,
    "use": "legacy redirect target",
    "loading": "lazy-near-section",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "hero-marina-webp",
    "publicPath": "/media/hero-marina.webp",
    "sourcePath": "assets/images/hero-marina.webp",
    "kind": "image",
    "width": 1600,
    "height": 1200,
    "bytes": 282742,
    "use": "legacy redirect target",
    "loading": "lazy-near-section",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "hero-palm-webp",
    "publicPath": "/media/hero-palm.webp",
    "sourcePath": "assets/images/hero-palm.webp",
    "kind": "image",
    "width": 1600,
    "height": 2400,
    "bytes": 372550,
    "use": "legacy redirect target",
    "loading": "lazy-near-section",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "hero-interior-webp",
    "publicPath": "/media/hero-interior.webp",
    "sourcePath": "assets/images/hero-interior.webp",
    "kind": "image",
    "width": 1600,
    "height": 1088,
    "bytes": 163088,
    "use": "consultation",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "buy-villa-editorial-webp",
    "publicPath": "/media/buy-villa-editorial.webp",
    "sourcePath": "OpenAI image generation, 2026-07-14",
    "kind": "image",
    "width": 1122,
    "height": 1402,
    "bytes": 210722,
    "use": "homepage buying route",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Generated for this site with OpenAI image generation"
  },
  {
    "id": "sell-villa-editorial-webp",
    "publicPath": "/media/sell-villa-editorial.webp",
    "sourcePath": "OpenAI image generation, 2026-07-14",
    "kind": "image",
    "width": 1122,
    "height": 1402,
    "bytes": 198670,
    "use": "homepage selling route",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Generated for this site with OpenAI image generation"
  },
  {
    "id": "inspection-editorial-webp",
    "publicPath": "/media/inspection-editorial.webp",
    "sourcePath": "OpenAI image generation, 2026-07-14",
    "kind": "image",
    "width": 1448,
    "height": 1086,
    "bytes": 99362,
    "use": "homepage editorial bridge",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Generated for this site with OpenAI image generation"
  },
  {
    "id": "business-bay-webp",
    "publicPath": "/media/business-bay.webp",
    "sourcePath": "assets/images/business-bay.webp",
    "kind": "image",
    "width": 1600,
    "height": 1068,
    "bytes": 173308,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "downtown-webp",
    "publicPath": "/media/downtown.webp",
    "sourcePath": "assets/images/downtown.webp",
    "kind": "image",
    "width": 1200,
    "height": 675,
    "bytes": 87104,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "dubai-hills-webp",
    "publicPath": "/media/dubai-hills.webp",
    "sourcePath": "assets/images/dubai-hills.webp",
    "kind": "image",
    "width": 1180,
    "height": 787,
    "bytes": 205506,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "dubai-islands-webp",
    "publicPath": "/media/dubai-islands.webp",
    "sourcePath": "assets/images/dubai-islands.webp",
    "kind": "image",
    "width": 720,
    "height": 405,
    "bytes": 47226,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository render, publication rights to confirm"
  },
  {
    "id": "dubai-marina-webp",
    "publicPath": "/media/dubai-marina.webp",
    "sourcePath": "assets/images/dubai-marina.webp",
    "kind": "image",
    "width": 1280,
    "height": 960,
    "bytes": 233624,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "palm-jumeirah-webp",
    "publicPath": "/media/palm-jumeirah.webp",
    "sourcePath": "assets/images/palm-jumeirah.webp",
    "kind": "image",
    "width": 1240,
    "height": 480,
    "bytes": 101720,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "saadiyat-webp",
    "publicPath": "/media/saadiyat.webp",
    "sourcePath": "assets/images/saadiyat.webp",
    "kind": "image",
    "width": 1600,
    "height": 1079,
    "bytes": 260858,
    "use": "area guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "the-wilds-webp",
    "publicPath": "/media/the-wilds.webp",
    "sourcePath": "assets/images/the-wilds.webp",
    "kind": "image",
    "width": 1500,
    "height": 844,
    "bytes": 248396,
    "use": "Dubailand guide",
    "loading": "route-priority",
    "fallback": null,
    "provenance": "Repository render, publication rights to confirm"
  },
  {
    "id": "og-areas-business-bay-jpg",
    "publicPath": "/media/og-areas/business-bay.jpg",
    "sourcePath": "assets/images/og-areas/business-bay.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 173677,
    "use": "Business Bay social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "og-areas-downtown-dubai-jpg",
    "publicPath": "/media/og-areas/downtown-dubai.jpg",
    "sourcePath": "assets/images/og-areas/downtown-dubai.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 138147,
    "use": "Downtown Dubai social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "og-areas-dubai-hills-jpg",
    "publicPath": "/media/og-areas/dubai-hills.jpg",
    "sourcePath": "assets/images/og-areas/dubai-hills.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 217500,
    "use": "Dubai Hills social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "og-areas-dubai-islands-jpg",
    "publicPath": "/media/og-areas/dubai-islands.jpg",
    "sourcePath": "assets/images/og-areas/dubai-islands.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 167967,
    "use": "Dubai Islands social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository render, publication rights to confirm"
  },
  {
    "id": "og-areas-dubai-marina-jpg",
    "publicPath": "/media/og-areas/dubai-marina.jpg",
    "sourcePath": "assets/images/og-areas/dubai-marina.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 217340,
    "use": "Dubai Marina social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "og-areas-dubailand-jpg",
    "publicPath": "/media/og-areas/dubailand.jpg",
    "sourcePath": "assets/images/og-areas/dubailand.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 275719,
    "use": "Dubailand social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository render, publication rights to confirm"
  },
  {
    "id": "og-areas-palm-jumeirah-jpg",
    "publicPath": "/media/og-areas/palm-jumeirah.jpg",
    "sourcePath": "assets/images/og-areas/palm-jumeirah.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 153421,
    "use": "Palm Jumeirah social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "og-areas-saadiyat-island-jpg",
    "publicPath": "/media/og-areas/saadiyat-island.jpg",
    "sourcePath": "assets/images/og-areas/saadiyat-island.jpg",
    "kind": "image",
    "width": 1200,
    "height": 630,
    "bytes": 206107,
    "use": "Saadiyat social metadata",
    "loading": "metadata",
    "fallback": null,
    "provenance": "Repository asset"
  },
  {
    "id": "iffy-hero-mp4",
    "publicPath": "/media/iffy-hero.mp4",
    "sourcePath": "assets/videos/iffy-hero.mp4",
    "kind": "video",
    "width": 480,
    "height": 848,
    "bytes": 802811,
    "use": "homepage portrait enhancement",
    "loading": "after-lcp",
    "fallback": "/media/iffy-hero-poster.webp",
    "provenance": "Repository asset"
  },
  {
    "id": "iffy-film-mp4",
    "publicPath": "/media/iffy-film.mp4",
    "sourcePath": "assets/videos/iffy-film.mp4",
    "kind": "video",
    "width": 1920,
    "height": 1080,
    "bytes": 14205227,
    "use": "advisor film, one placement",
    "loading": "explicit-play",
    "fallback": "/media/iffy-film-poster.webp",
    "provenance": "Repository asset"
  },
  {
    "id": "iffy-film-poster-webp",
    "publicPath": "/media/iffy-film-poster.webp",
    "sourcePath": "assets/images/iffy-film-poster.webp",
    "kind": "image",
    "width": 760,
    "height": 1350,
    "bytes": 29224,
    "use": "advisor film poster",
    "loading": "lazy",
    "fallback": null,
    "provenance": "Frame extracted from repository film"
  },
  {
    "id": "iffy-film-vtt",
    "publicPath": "/media/iffy-film.vtt",
    "sourcePath": "assets/videos/iffy-film.vtt",
    "kind": "track",
    "width": null,
    "height": null,
    "bytes": 1587,
    "use": "advisor film captions",
    "loading": "with-film",
    "fallback": null,
    "provenance": "Repository caption draft, verify against audio before launch"
  }
] satisfies MediaAsset[];
